/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface S3BatchEvent {
    invocationSchemaVersion: string
    invocationId: string
    job: S3BatchEventJob
    tasks: S3BatchEventTask[]
}

export interface S3BatchEventJob {
    id: string
}

export interface S3BatchEventTask {
    taskId: string
    s3Key: string
    s3VersionId: string | null
    s3BucketArn: string
}
