/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface SnsMsgAttribute {
    Type: string
    Value: string
}

export interface SnsNotificationSchema {
    Subject?: string | null | undefined
    TopicArn: string
    UnsubscribeUrl: string
    UnsubscribeURL?: string | undefined
    SigningCertUrl?: string | undefined
    SigningCertURL?: string | undefined
    Type: 'Notification'
    MessageAttributes?:
        | {
              [k: string]: SnsMsgAttribute | undefined
          }
        | undefined
    Message: string
    MessageId: string
    Signature?: string | undefined
    SignatureVersion?: string | undefined
    Timestamp: string
}

export interface SnsRecordSchema {
    EventSource: 'aws:sns'
    EventVersion: string
    EventSubscriptionArn: string
    Sns: SnsNotificationSchema
}

export interface SnsSchema {
    Records: [SnsRecordSchema, ...SnsRecordSchema[]]
}
