/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface KafkaMskEventSchema {
    bootstrapServers?: string | null | undefined
    records: {
        [k: string]: KafkaRecordSchema[] | undefined
    }
    eventSource: 'aws:kafka'
    eventSourceArn: string
}

export interface KafkaRecordSchema {
    topic: string
    partition: number
    offset: number
    timestamp: number
    timestampType: string
    key: string
    value: string
    headers: {
        [k: string]: number[] | undefined
    }[]
}

export interface KafkaSelfManagedEventSchema {
    bootstrapServers?: string | null | undefined
    records: {
        [k: string]: KafkaRecordSchema[] | undefined
    }
    eventSource: 'SelfManagedKafka'
}
