/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
// biome-ignore-all lint: this file is generated
/* eslint-disable */

export interface EventBridgeSchema {
    version: string
    id: string
    source: string
    account: string
    time: string
    region: string
    resources: string[]
    'detail-type': string
    detail: unknown
    'replay-name'?: string | undefined
}
