/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface EventBridgeSchema {
    version: string
    id: string
    source: string
    account: string
    time: string
    region: string
    resources: string[]
    'detail-type': string
    detail: unknown
    'replay-name'?: string | undefined
}
