/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface AlbMultiValueHeadersSchema {
    httpMethod: string
    path: string
    body: string
    isBase64Encoded: boolean
    headers?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    queryStringParameters?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    requestContext: {
        elb: {
            targetGroupArn: string
        }
    }
    multiValueHeaders: {
        [k: string]: string[] | undefined
    }
    multiValueQueryStringParameters: {
        [k: string]: string[] | undefined
    }
}

export interface AlbSchema {
    httpMethod: string
    path: string
    body: string
    isBase64Encoded: boolean
    headers?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    queryStringParameters?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    requestContext: {
        elb: {
            targetGroupArn: string
        }
    }
}
