version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: 'never'
    ignore:
      - dependency-name: '*'
