/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'
import { Status } from '../../lib/models.type'

export interface Query {
    status: Status
}

export const Query = {
    validate: require('./schemas/query.schema.js') as ValidateFunction<Query>,
    get schema() {
        return Query.validate.schema
    },
    is: (o: unknown): o is Query => Query.validate(o) === true,
    assert: (o: unknown) => {
        if (!Query.validate(o)) {
            throw new AjvValidator.ValidationError(Query.validate.errors ?? [])
        }
    },
} as const
