/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import type { ValidateFunction } from 'ajv'
import { ValidationError } from 'ajv'
import { type Status } from '../../lib/models.type.js'

export interface Query {
    status: Status
}

export const Query = {
    validate: (await import('./schemas/query.schema.js')).validate as ValidateFunction<Query>,
    get schema() {
        return Query.validate.schema
    },
    get errors() {
        return Query.validate.errors ?? undefined
    },
    is: (o: unknown): o is Query => Query.validate(o) === true,
    assert: (o: unknown) => {
        if (!Query.validate(o)) {
            throw new ValidationError(Query.errors ?? [])
        }
    },
} as const
