/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface DynamoDBStreamChangeRecord {
    ApproximateCreationDateTime?: number | undefined
    Keys: {
        [k: string]:
            | {
                  [k: string]: unknown
              }
            | undefined
    }
    NewImage?:
        | {
              [k: string]: unknown
          }
        | undefined
    OldImage?:
        | {
              [k: string]: unknown
          }
        | undefined
    SequenceNumber: string
    SizeBytes: number
    StreamViewType: 'NEW_IMAGE' | 'OLD_IMAGE' | 'NEW_AND_OLD_IMAGES' | 'KEYS_ONLY'
}

export interface DynamoDBStreamRecord {
    eventID: string
    eventName: 'INSERT' | 'MODIFY' | 'REMOVE'
    eventVersion: string
    eventSource: 'aws:dynamodb'
    awsRegion: string
    eventSourceARN: string
    dynamodb: DynamoDBStreamChangeRecord
    userIdentity?: UserIdentity | undefined
}

export interface DynamoDBStreamSchema {
    Records: [DynamoDBStreamRecord, ...DynamoDBStreamRecord[]]
}

export interface UserIdentity {
    type: 'Service'
    principalId: 'dynamodb.amazonaws.com'
}
