/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as S3EventRecordValidator } from './schemas/s3-event-record.schema.js'
import { validate as S3EventValidator } from './schemas/s3-event.schema.js'

export interface S3Event {
    Records: S3EventRecord[]
}

export const S3Event = {
    validate: S3EventValidator as ValidateFunction<S3Event>,
    get schema() {
        return S3Event.validate.schema
    },
    get errors() {
        return S3Event.validate.errors ?? undefined
    },
    is: (o: unknown): o is S3Event => S3Event.validate(o) === true,
    parse: (o: unknown): { right: S3Event } | { left: DefinedError[] } => {
        if (S3Event.is(o)) {
            return { right: o }
        }
        return { left: (S3Event.errors ?? []) as DefinedError[] }
    },
} as const

export interface S3EventRecord {
    eventVersion: string
    eventSource: string
    awsRegion: string
    eventTime: string
    eventName: string
    userIdentity: {
        principalId: string
    }
    requestParameters: {
        sourceIPAddress: string
    }
    responseElements: {
        'x-amz-request-id': string
        'x-amz-id-2': string
    }
    s3: {
        s3SchemaVersion: string
        configurationId: string
        bucket: {
            name: string
            ownerIdentity: {
                principalId: string
            }
            arn: string
        }
        object: {
            key: string
            size: number
            eTag: string
            versionId?: string | undefined
            sequencer: string
        }
    }
    glacierEventData?:
        | {
              restoreEventData: {
                  lifecycleRestorationExpiryTime: string
                  lifecycleRestoreStorageClass: string
              }
          }
        | undefined
}

export const S3EventRecord = {
    validate: S3EventRecordValidator as ValidateFunction<S3EventRecord>,
    get schema() {
        return S3EventRecord.validate.schema
    },
    get errors() {
        return S3EventRecord.validate.errors ?? undefined
    },
    is: (o: unknown): o is S3EventRecord => S3EventRecord.validate(o) === true,
    parse: (o: unknown): { right: S3EventRecord } | { left: DefinedError[] } => {
        if (S3EventRecord.is(o)) {
            return { right: o }
        }
        return { left: (S3EventRecord.errors ?? []) as DefinedError[] }
    },
} as const

export interface S3EventRecordGlacierEventData {
    restoreEventData: {
        lifecycleRestorationExpiryTime: string
        lifecycleRestoreStorageClass: string
    }
}
