/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as SNSEventRecordValidator } from './schemas/sns-event-record.schema.js'
import { validate as SNSEventValidator } from './schemas/sns-event.schema.js'

export interface SNSEvent {
    Records: SNSEventRecord[]
}

export const SNSEvent = {
    validate: SNSEventValidator as ValidateFunction<SNSEvent>,
    get schema() {
        return SNSEvent.validate.schema
    },
    get errors() {
        return SNSEvent.validate.errors ?? undefined
    },
    is: (o: unknown): o is SNSEvent => SNSEvent.validate(o) === true,
    parse: (o: unknown): { right: SNSEvent } | { left: DefinedError[] } => {
        if (SNSEvent.is(o)) {
            return { right: o }
        }
        return { left: (SNSEvent.errors ?? []) as DefinedError[] }
    },
} as const

export interface SNSEventRecord {
    EventVersion: string
    EventSubscriptionArn: string
    EventSource: string
    Sns: SNSMessage
}

export const SNSEventRecord = {
    validate: SNSEventRecordValidator as ValidateFunction<SNSEventRecord>,
    get schema() {
        return SNSEventRecord.validate.schema
    },
    get errors() {
        return SNSEventRecord.validate.errors ?? undefined
    },
    is: (o: unknown): o is SNSEventRecord => SNSEventRecord.validate(o) === true,
    parse: (o: unknown): { right: SNSEventRecord } | { left: DefinedError[] } => {
        if (SNSEventRecord.is(o)) {
            return { right: o }
        }
        return { left: (SNSEventRecord.errors ?? []) as DefinedError[] }
    },
} as const

export interface SNSMessage {
    SignatureVersion: string
    Timestamp: string
    Signature: string
    SigningCertUrl: string
    MessageId: string
    Message: string
    MessageAttributes: SNSMessageAttributes
    Type: string
    UnsubscribeUrl: string
    TopicArn: string
    Subject?: string | undefined
    Token?: string | undefined
}

export interface SNSMessageAttribute {
    Type: string
    Value: string
}

export interface SNSMessageAttributes {
    [k: string]: SNSMessageAttribute | undefined
}
