/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { DefinedError, ValidateFunction } from 'ajv'

import { validate as EventBridgeEventValidator } from './schemas/event-bridge-event.schema.js'

export interface EventBridgeEvent {
    id: string
    version: string
    account: string
    time: string
    region: string
    resources: string[]
    source: string
    'detail-type': string
    detail: unknown
    'replay-name'?: string | undefined
}

export const EventBridgeEvent = {
    validate: EventBridgeEventValidator as ValidateFunction<EventBridgeEvent>,
    get schema() {
        return EventBridgeEvent.validate.schema
    },
    get errors() {
        return EventBridgeEvent.validate.errors ?? undefined
    },
    is: (o: unknown): o is EventBridgeEvent => EventBridgeEvent.validate(o) === true,
    parse: (o: unknown): { right: EventBridgeEvent } | { left: DefinedError[] } => {
        if (EventBridgeEvent.is(o)) {
            return { right: o }
        }
        return { left: (EventBridgeEvent.errors ?? []) as DefinedError[] }
    },
} as const
