/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { APIGatewayCert, APIGatewayHttpMethod } from './proxy.type.js'

export interface APIGatewayEventRequestContextV2 {
    accountId: string
    apiId: string
    authorizer?: RequestContextV2Authorizer
    authentication?:
        | {
              clientCert?: APIGatewayCert | undefined
          }
        | null
        | undefined
    domainName: string
    domainPrefix: string
    http: RequestContextV2Http
    requestId: string
    routeKey: string
    stage: string
    time: string
    timeEpoch: number
}

export interface APIGatewayProxyEventV2Schema {
    version: string
    routeKey: string
    rawPath: string
    rawQueryString: string
    cookies?: string[] | undefined
    headers: {
        [k: string]: string | undefined
    }
    queryStringParameters?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    requestContext: APIGatewayEventRequestContextV2
    body?: string | undefined
    pathParameters?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    isBase64Encoded: boolean
    stageVariables?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
}

export interface APIGatewayRequestAuthorizerEventV2Schema {
    version: '2.0'
    type: 'REQUEST'
    routeArn: string
    identitySource: string[]
    routeKey: string
    rawPath: string
    rawQueryString: string
    cookies?: string[] | undefined
    headers?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    queryStringParameters?:
        | {
              [k: string]: string | undefined
          }
        | undefined
    requestContext: APIGatewayEventRequestContextV2
    pathParameters?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    stageVariables?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
}

export type RequestContextV2Authorizer =
    | {
          jwt?:
              | {
                    claims: {
                        [k: string]: unknown
                    }
                    scopes: string[] | null
                }
              | undefined
          iam?:
              | {
                    accessKey?: string | undefined
                    accountId?: string | undefined
                    callerId?: string | undefined
                    principalOrgId?: string | null | undefined
                    userArn?: string | undefined
                    userId?: string | undefined
                    cognitoIdentity?:
                        | {
                              amr: string[]
                              identityId: string
                              identityPoolId: string
                          }
                        | null
                        | undefined
                }
              | undefined
          lambda?:
              | {
                    [k: string]: unknown
                }
              | null
              | undefined
      }
    | undefined

export interface RequestContextV2Http {
    method: keyof typeof APIGatewayHttpMethod
    path: string
    protocol: string
    sourceIp: string
    userAgent: string
}
