/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface APIGatewayCert {
    clientCertPem: string
    subjectDN: string
    issuerDN: string
    serialNumber: string
    validity: {
        notBefore: string
        notAfter: string
    }
}

export const APIGatewayHttpMethod = {
    GET: 'GET',
    POST: 'POST',
    PUT: 'PUT',
    PATCH: 'PATCH',
    DELETE: 'DELETE',
    HEAD: 'HEAD',
    OPTIONS: 'OPTIONS',
} as const
export type APIGatewayHttpMethod = typeof APIGatewayHttpMethod

export type APIGatewayRecord = {
    [k: string]: string | undefined
} | null
