/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { APIGatewayCert, APIGatewayHttpMethod, APIGatewayRecord } from './proxy.type.js'

export interface APIGatewayEventIdentity {
    accessKey?: string | null | undefined
    accountId?: string | null | undefined
    apiKey?: string | null | undefined
    apiKeyId?: string | null | undefined
    caller?: string | null | undefined
    cognitoAuthenticationProvider?: string | null | undefined
    cognitoAuthenticationType?: string | null | undefined
    cognitoIdentityId?: string | null | undefined
    cognitoIdentityPoolId?: string | null | undefined
    principalOrgId?: string | null | undefined
    sourceIp?: (string | 'test-invoke-source-ip') | undefined
    user?: string | null | undefined
    userAgent?: string | null | undefined
    userArn?: string | null | undefined
    clientCert?: APIGatewayCert | null | undefined
}

export type APIGatewayEventRequestAuthorizer =
    | (
          | {
                integrationLatency: number
                principalId: string
            }
          | {
                claims: {
                    [k: string]: unknown
                }
                scopes?: string[] | undefined
            }
      )
    | null
    | undefined

export interface APIGatewayEventRequestContext {
    accountId: string
    apiId: string
    deploymentId?: string | null | undefined
    authorizer?: APIGatewayEventRequestAuthorizer
    stage: string
    protocol: string
    identity: APIGatewayEventIdentity
    requestId: string
    requestTime: string
    requestTimeEpoch: number
    resourceId?: string | null | undefined
    resourcePath: string
    domainName?: string | null | undefined
    domainPrefix?: string | null | undefined
    extendedRequestId?: string | null | undefined
    httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS'
    path: string
    connectedAt?: number | null | undefined
    connectionId?: string | null | undefined
    eventType?: 'CONNECT' | 'MESSAGE' | 'DISCONNECT' | null | undefined
    messageDirection?: string | null | undefined
    messageId?: string | null | undefined
    routeKey?: string | null | undefined
    operationName?: string | null | undefined
}

export interface APIGatewayProxyEventSchema {
    resource: string
    path: string
    httpMethod: keyof typeof APIGatewayHttpMethod
    headers?: APIGatewayRecord | null | undefined
    multiValueHeaders?:
        | {
              [k: string]: string[] | undefined
          }
        | null
        | undefined
    queryStringParameters: {
        [k: string]: string | undefined
    } | null
    multiValueQueryStringParameters: {
        [k: string]: string[] | undefined
    } | null
    pathParameters?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    stageVariables?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    requestContext: APIGatewayEventRequestContext
    body: string | null
    isBase64Encoded: boolean
}

export interface APIGatewayRequestAuthorizerEventSchema {
    type: 'REQUEST'
    methodArn: string
    resource: string
    path: string
    httpMethod: keyof typeof APIGatewayHttpMethod
    headers: {
        [k: string]: string | undefined
    }
    multiValueHeaders: {
        [k: string]: string[] | undefined
    }
    queryStringParameters: {
        [k: string]: string | undefined
    }
    multiValueQueryStringParameters: {
        [k: string]: string[] | undefined
    }
    pathParameters: {
        [k: string]: string | undefined
    }
    stageVariables: {
        [k: string]: string | undefined
    }
    requestContext: APIGatewayEventRequestContext
    domainName?: string | undefined
    deploymentId?: string | undefined
    apiId?: string | undefined
}

export interface APIGatewayTokenAuthorizerEventSchema {
    type: 'TOKEN'
    authorizationToken: string
    methodArn: string
}
