/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

import type { APIGatewayCert } from './http.type.js'
import { validate as APIGatewayEventRequestContextValidator } from './schemas/api-gateway-event-request-context.schema.js'
import { validate as APIGatewayProxyEventSchemaValidator } from './schemas/api-gateway-proxy-event-schema.schema.js'
import { validate as APIGatewayRequestAuthorizerEventSchemaValidator } from './schemas/api-gateway-request-authorizer-event-schema.schema.js'
import { validate as APIGatewayTokenAuthorizerEventSchemaValidator } from './schemas/api-gateway-token-authorizer-event-schema.schema.js'

import type { DefinedError, ValidateFunction } from 'ajv'

export interface APIGatewayEventIdentity {
    accessKey?: string | null | undefined
    accountId?: string | null | undefined
    apiKey?: string | null | undefined
    apiKeyId?: string | null | undefined
    caller?: string | null | undefined
    cognitoAuthenticationProvider?: string | null | undefined
    cognitoAuthenticationType?: string | null | undefined
    cognitoIdentityId?: string | null | undefined
    cognitoIdentityPoolId?: string | null | undefined
    principalOrgId?: string | null | undefined
    sourceIp?: (string | 'test-invoke-source-ip') | undefined
    user?: string | null | undefined
    userAgent?: string | null | undefined
    userArn?: string | null | undefined
    clientCert?: APIGatewayCert | null | undefined
}

export interface APIGatewayEventRequestContext {
    accountId: string
    apiId: string
    deploymentId?: string | null | undefined
    authorizer?:
        | (
              | {
                    integrationLatency: number
                    principalId: string
                }
              | {
                    claims: {
                        [k: string]: unknown
                    }
                    scopes?: string[] | undefined
                }
          )
        | null
        | undefined
    stage: string
    protocol: string
    identity: APIGatewayEventIdentity
    requestId: string
    requestTime: string
    requestTimeEpoch: number
    resourceId?: string | null | undefined
    resourcePath: string
    domainName?: string | null | undefined
    domainPrefix?: string | null | undefined
    extendedRequestId?: string | null | undefined
    httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS'
    path: string
    connectedAt?: number | null | undefined
    connectionId?: string | null | undefined
    eventType?: 'CONNECT' | 'MESSAGE' | 'DISCONNECT' | null | undefined
    messageDirection?: string | null | undefined
    messageId?: string | null | undefined
    routeKey?: string | null | undefined
    operationName?: string | null | undefined
}

export const APIGatewayEventRequestContext = {
    validate: APIGatewayEventRequestContextValidator as ValidateFunction<APIGatewayEventRequestContext>,
    get schema() {
        return APIGatewayEventRequestContext.validate.schema
    },
    get errors() {
        return APIGatewayEventRequestContext.validate.errors ?? undefined
    },
    is: (o: unknown): o is APIGatewayEventRequestContext => APIGatewayEventRequestContext.validate(o) === true,
    parse: (o: unknown): { right: APIGatewayEventRequestContext } | { left: DefinedError[] } => {
        if (APIGatewayEventRequestContext.is(o)) {
            return { right: o }
        }
        return { left: (APIGatewayEventRequestContext.errors ?? []) as DefinedError[] }
    },
} as const

export interface APIGatewayProxyEventSchema {
    resource: string
    path: string
    httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS'
    headers?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    multiValueHeaders?:
        | {
              [k: string]: string[] | undefined
          }
        | null
        | undefined
    queryStringParameters: {
        [k: string]: string | undefined
    } | null
    multiValueQueryStringParameters: {
        [k: string]: string[] | undefined
    } | null
    pathParameters?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    stageVariables?:
        | {
              [k: string]: string | undefined
          }
        | null
        | undefined
    requestContext: APIGatewayEventRequestContext
    body: string | null
    isBase64Encoded: boolean
}

export const APIGatewayProxyEventSchema = {
    validate: APIGatewayProxyEventSchemaValidator as ValidateFunction<APIGatewayProxyEventSchema>,
    get schema() {
        return APIGatewayProxyEventSchema.validate.schema
    },
    get errors() {
        return APIGatewayProxyEventSchema.validate.errors ?? undefined
    },
    is: (o: unknown): o is APIGatewayProxyEventSchema => APIGatewayProxyEventSchema.validate(o) === true,
    parse: (o: unknown): { right: APIGatewayProxyEventSchema } | { left: DefinedError[] } => {
        if (APIGatewayProxyEventSchema.is(o)) {
            return { right: o }
        }
        return { left: (APIGatewayProxyEventSchema.errors ?? []) as DefinedError[] }
    },
} as const

export interface APIGatewayRequestAuthorizerEventSchema {
    type: 'REQUEST'
    methodArn: string
    resource: string
    path: string
    httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS'
    headers: {
        [k: string]: string | undefined
    }
    multiValueHeaders: {
        [k: string]: string[] | undefined
    }
    queryStringParameters: {
        [k: string]: string | undefined
    }
    multiValueQueryStringParameters: {
        [k: string]: string[] | undefined
    }
    pathParameters: {
        [k: string]: string | undefined
    }
    stageVariables: {
        [k: string]: string | undefined
    }
    requestContext: APIGatewayEventRequestContext
    domainName?: string | undefined
    deploymentId?: string | undefined
    apiId?: string | undefined
}

export const APIGatewayRequestAuthorizerEventSchema = {
    validate: APIGatewayRequestAuthorizerEventSchemaValidator as ValidateFunction<APIGatewayRequestAuthorizerEventSchema>,
    get schema() {
        return APIGatewayRequestAuthorizerEventSchema.validate.schema
    },
    get errors() {
        return APIGatewayRequestAuthorizerEventSchema.validate.errors ?? undefined
    },
    is: (o: unknown): o is APIGatewayRequestAuthorizerEventSchema => APIGatewayRequestAuthorizerEventSchema.validate(o) === true,
    parse: (o: unknown): { right: APIGatewayRequestAuthorizerEventSchema } | { left: DefinedError[] } => {
        if (APIGatewayRequestAuthorizerEventSchema.is(o)) {
            return { right: o }
        }
        return { left: (APIGatewayRequestAuthorizerEventSchema.errors ?? []) as DefinedError[] }
    },
} as const

export interface APIGatewayTokenAuthorizerEventSchema {
    type: 'TOKEN'
    authorizationToken: string
    methodArn: string
}

export const APIGatewayTokenAuthorizerEventSchema = {
    validate: APIGatewayTokenAuthorizerEventSchemaValidator as ValidateFunction<APIGatewayTokenAuthorizerEventSchema>,
    get schema() {
        return APIGatewayTokenAuthorizerEventSchema.validate.schema
    },
    get errors() {
        return APIGatewayTokenAuthorizerEventSchema.validate.errors ?? undefined
    },
    is: (o: unknown): o is APIGatewayTokenAuthorizerEventSchema => APIGatewayTokenAuthorizerEventSchema.validate(o) === true,
    parse: (o: unknown): { right: APIGatewayTokenAuthorizerEventSchema } | { left: DefinedError[] } => {
        if (APIGatewayTokenAuthorizerEventSchema.is(o)) {
            return { right: o }
        }
        return { left: (APIGatewayTokenAuthorizerEventSchema.errors ?? []) as DefinedError[] }
    },
} as const
