/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface SesMail {
    timestamp: string
    source: string
    messageId: string
    destination: string[]
    headersTruncated: boolean
    headers: {
        name: string
        value: string
    }[]
    commonHeaders: {
        from: string[]
        to: string[]
        cc?: string[] | undefined
        bcc?: string[] | undefined
        sender?: string[] | undefined
        'reply-to'?: string[] | undefined
        returnPath: string
        messageId: string
        date: string
        subject: string
    }
}

export interface SesMessage {
    mail: SesMail
    receipt: SesReceipt
}

export interface SesReceipt {
    timestamp: string
    processingTimeMillis: number
    recipients: string[]
    spamVerdict: SesReceiptVerdict
    virusVerdict: SesReceiptVerdict
    spfVerdict: SesReceiptVerdict
    dmarcVerdict: SesReceiptVerdict
    dkimVerdict: SesReceiptVerdict
    dmarcPolicy: 'none' | 'quarantine' | 'reject'
    action: {
        type: 'Lambda'
        invocationType: 'Event'
        functionArn: string
    }
}

export interface SesReceiptVerdict {
    status: 'PASS' | 'FAIL' | 'GRAY' | 'PROCESSING_FAILED'
}

export interface SesRecordSchema {
    eventSource: 'aws:ses'
    eventVersion: string
    ses: SesMessage
}

export interface SesSchema {
    Records: [SesRecordSchema, ...SesRecordSchema[]]
}
