/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
/* eslint-disable */

export interface SecretRotationEvent {
    Step: 'createSecret' | 'finishSecret' | 'setSecret' | 'testSecret'
    SecretId: string
    ClientRequestToken: string
}
