/**
 * Generated by @skyleague/therefore
 * Do not manually touch this
 */
// biome-ignore-all lint: this file is generated
/* eslint-disable */

export interface SecretRotationEvent {
    Step: 'createSecret' | 'finishSecret' | 'setSecret' | 'testSecret'
    SecretId: string
    ClientRequestToken: string
}
