/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface SqsAttributesSchema {
    ApproximateReceiveCount: string
    ApproximateFirstReceiveTimestamp: string
    MessageDeduplicationId?: string | undefined
    MessageGroupId?: string | undefined
    SenderId: string
    SentTimestamp: string
    SequenceNumber?: string | undefined
    AWSTraceHeader?: string | undefined
    DeadLetterQueueSourceArn?: string | undefined
}

export interface SqsMsgAttributeSchema {
    stringValue?: string | undefined
    binaryValue?: string | undefined
    stringListValues?: string[] | undefined
    binaryListValues?: string[] | undefined
    dataType: string
}

export interface SqsRecordSchema {
    messageId: string
    receiptHandle: string
    body: string
    attributes: SqsAttributesSchema
    messageAttributes: {
        [k: string]: SqsMsgAttributeSchema | undefined
    }
    md5OfBody: string
    md5OfMessageAttributes?: string | null | undefined
    eventSource: 'aws:sqs'
    eventSourceARN: string
    awsRegion: string
}

export interface SqsSchema {
    Records: SqsRecordSchema[]
}
